main: net.pyrolands.root.main
name: QuickGM
version: 1.0-RELEASE
description: "Changes between CREATIVE and SURIVAL with '/gm' command"
api-version: 1.14
author: turner#6040
permissions:
  essentials.gamemode:
    description: Access to /<command>
commands:
  gm:
    usage: /<command>
    permission: essentials.gamemode